"""Added firebase_uid

Revision ID: 264a159de06a
Revises: 
Create Date: 2025-03-15 14:51:00.549172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '264a159de06a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('animal_owner', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['firebase_uid'])

    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('firebase_uid', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['firebase_uid'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')

    with op.batch_alter_table('animal_owner', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('firebase_uid')

    # ### end Alembic commands ###
