"""Initial migration

Revision ID: a4e206cd62de
Revises: 
Create Date: 2025-03-11 16:38:33.085742

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a4e206cd62de'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appointment')
    op.drop_table('healthrecord')
    op.drop_table('payment')
    op.drop_table('notification')
    with op.batch_alter_table('animalowner', schema=None) as batch_op:
        batch_op.drop_index('email')

    op.drop_table('animalowner')
    op.drop_table('vetreviews')
    op.drop_table('consultation')
    op.drop_table('animal')
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('license_number',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('national_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=50),
               existing_nullable=False)
        batch_op.alter_column('clinic',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               existing_nullable=False)
        batch_op.alter_column('specialization',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=200),
               nullable=False)
        batch_op.create_unique_constraint(None, ['national_id'])
        batch_op.create_unique_constraint(None, ['license_number'])
        batch_op.drop_column('created_at')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('veterinarian', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('specialization',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('clinic',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('national_id',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('license_number',
               existing_type=sa.String(length=50),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    op.create_table('animal',
    sa.Column('animal_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('species', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('breed', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('age', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['animalowner.owner_id'], name='animal_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('animal_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('consultation',
    sa.Column('consultation_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', mysql.TEXT(), nullable=True),
    sa.Column('prescription', mysql.TEXT(), nullable=True),
    sa.Column('consultation_date', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], name='consultation_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarian.id'], name='consultation_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('consultation_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('vetreviews',
    sa.Column('review_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('rating', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('review', mysql.TEXT(), nullable=True),
    sa.Column('review_date', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.CheckConstraint('(`rating` between 1 and 5)', name='vetreviews_chk_1'),
    sa.ForeignKeyConstraint(['owner_id'], ['animalowner.owner_id'], name='vetreviews_ibfk_2', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarian.id'], name='vetreviews_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('review_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('animalowner',
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('address', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('owner_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('animalowner', schema=None) as batch_op:
        batch_op.create_index('email', ['email'], unique=True)

    op.create_table('notification',
    sa.Column('notification_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', mysql.TEXT(), nullable=True),
    sa.Column('is_read', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['animalowner.owner_id'], name='notification_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notification_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('payment',
    sa.Column('payment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('amount', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_status', mysql.ENUM('Pending', 'Completed', 'Failed'), server_default=sa.text("'Pending'"), nullable=True),
    sa.Column('payment_method', mysql.ENUM('Credit Card', 'PayPal', 'Cash', 'Insurance'), nullable=True),
    sa.Column('transaction_date', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointment.appointment_id'], name='payment_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('payment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('healthrecord',
    sa.Column('record_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('animal_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('diagnosis', mysql.TEXT(), nullable=True),
    sa.Column('treatment', mysql.TEXT(), nullable=True),
    sa.Column('date', sa.DATE(), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], name='healthrecord_ibfk_1', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('record_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('appointment',
    sa.Column('appointment_id', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('owner_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('vet_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('animal_id', mysql.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('appointment_date', mysql.DATETIME(), nullable=True),
    sa.Column('status', mysql.ENUM('Scheduled', 'Completed', 'Cancelled'), server_default=sa.text("'Scheduled'"), nullable=True),
    sa.ForeignKeyConstraint(['animal_id'], ['animal.animal_id'], name='appointment_ibfk_3', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['animalowner.owner_id'], name='appointment_ibfk_1', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vet_id'], ['veterinarian.id'], name='appointment_ibfk_2', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('appointment_id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
